# Matter Directories
#----------------------------------------#
set(MATTER_DIR        "${BASEDIR}/component/application/matter")
set(MATTER_CMAKEDIR   "${MATTER_DIR}/project/cmake")
set(CHIPDIR           "${BASEDIR}/third_party/connectedhomeip")
set(MATTER_EXAMPLEDIR "${MATTER_DIR}/examples")
set(MATTER_TOOLDIR    "${MATTER_DIR}/tools")
set(MATTER_DRIVER     "${MATTER_DIR}/drivers/matter_drivers")

# Matter Options
#----------------------------------------#
if(CONFIG_BLE_MATTER_ADAPTER)
    option(CHIP_ENABLE_CHIPOBLE      "Enable BLE for Matter"            ON)
else()
    option(CHIP_ENABLE_CHIPOBLE      "Disable BLE for Matter"           OFF)
endif()

if(CONFIG_MATTER_ENABLE_IPV4)
    option(CHIP_ENABLE_IPV4          "Enable IPv4 for Matter"           ON)
else()
    option(CHIP_ENABLE_IPV4          "Disable IPv4 for Matter"          OFF)
endif()

if(MATTER_EXAMPLE STREQUAL "bridge_port") #OTA is disabled for bridge_port example zap
    option(CHIP_ENABLE_OTA_REQUESTOR "Disable OTA Requestor for Matter" OFF)
else()
    option(CHIP_ENABLE_OTA_REQUESTOR "Enable OTA Requestor for Matter"  ON)
endif()

if(CONFIG_MATTER_ENABLE_SHELL)
    option(CHIP_ENABLE_SHELL         "Enable Shell for Matter"          ON)
else()
    option(CHIP_ENABLE_SHELL         "Disable Shell for Matter"         OFF)
endif()

if(CONFIG_MATTER_TC_EN)
    option(CHIP_ENABLE_TC            "Enable T&C for Matter"            ON)
else()
    option(CHIP_ENABLE_TC            "Disable T&C for Matter"           OFF)
endif()

# Matter General cmakes
#----------------------------------------#
set(MATTER_INCLUDE        "${MATTER_CMAKEDIR}/matter.cmake")
set(GENERATE_ARGS_GN      "${MATTER_CMAKEDIR}/utilities/generate_args_gn.cmake")
set(GENERATE_CLUSTER_FILE "${MATTER_CMAKEDIR}/utilities/generate_cluster_file.cmake")

# Matter Zap File, Cluster File, and Output directory list
#----------------------------------------#
set(ALL_CLUSTERS_OUTPUT_DIR       "${CHIPDIR}/examples/all-clusters-app/ameba/build/chip")
set(ALL_CLUSTERS_FILE             "${ALL_CLUSTERS_OUTPUT_DIR}/codegen/cluster-file.txt")
set(ALL_CLUSTERS_ZAP              "${CHIPDIR}/examples/all-clusters-app/all-clusters-common/all-clusters-app.zap")
set(AIR_PURIFIER_OUTPUT_DIR       "${CHIPDIR}/examples/air-purifier-app/ameba/build/chip")
set(AIR_PURIFIER_FILE             "${AIR_PURIFIER_OUTPUT_DIR}/codegen/cluster-file.txt")
set(AIR_PURIFIER_ZAP              "${CHIPDIR}/examples/air-purifier-app/air-purifier-common/air-purifier-app.zap")
set(BRIDGE_PORT_OUTPUT_DIR        "${CHIPDIR}/examples/bridge-app/ameba/build/chip")
set(BRIDGE_PORT_FILE              "${BRIDGE_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(BRIDGE_PORT_ZAP               "${CHIPDIR}/examples/bridge-app/bridge-common/bridge-app.zap")
set(LIGHTING_OUTPUT_DIR           "${CHIPDIR}/examples/lighting-app/ameba/build/chip")
set(LIGHTING_FILE                 "${LIGHTING_OUTPUT_DIR}/codegen/cluster-file.txt")
set(LIGHTING_ZAP                  "${CHIPDIR}/examples/lighting-app/lighting-common/lighting-app.zap")
set(THERMOSTAT_PORT_OUTPUT_DIR    "${CHIPDIR}/examples/thermostat/ameba/build/chip")
set(THERMOSTAT_PORT_FILE          "${THERMOSTAT_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(THERMOSTAT_PORT_ZAP           "${CHIPDIR}/examples/thermostat/thermostat-common/thermostat.zap")

set(AIRCON_PORT_OUTPUT_DIR        "${MATTER_EXAMPLEDIR}/aircon/build/chip")
set(AIRCON_PORT_FILE              "${AIRCON_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(AIRCON_PORT_ZAP               "${MATTER_EXAMPLEDIR}/aircon/aircon-app.zap")
set(BRIDGE_DM_OUTPUT_DIR          "${MATTER_EXAMPLEDIR}/bridge_dm/build/chip")
set(BRIDGE_DM_FILE                "${BRIDGE_DM_OUTPUT_DIR}/codegen/cluster-file.txt")
set(BRIDGE_DM_ZAP                 "${MATTER_EXAMPLEDIR}/bridge_dm/bridge-app.zap")
set(DISHWASHER_PORT_OUTPUT_DIR    "${MATTER_EXAMPLEDIR}/dishwasher/build/chip")
set(DISHWASHER_PORT_FILE          "${DISHWASHER_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(DISHWASHER_PORT_ZAP           "${MATTER_EXAMPLEDIR}/dishwasher/dishwasher-app.zap")
set(FAN_PORT_OUTPUT_DIR           "${MATTER_EXAMPLEDIR}/fan/build/chip")
set(FAN_PORT_FILE                 "${FAN_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(FAN_PORT_ZAP                  "${MATTER_EXAMPLEDIR}/fan/fan-app.zap")
set(LAUNDRYWASHER_PORT_OUTPUT_DIR "${MATTER_EXAMPLEDIR}/laundrywasher/build/chip")
set(LAUNDRYWASHER_PORT_FILE       "${LAUNDRYWASHER_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(LAUNDRYWASHER_PORT_ZAP        "${MATTER_EXAMPLEDIR}/laundrywasher/laundrywasher-app.zap")
set(MICROWAVEOVEN_PORT_OUTPUT_DIR "${MATTER_EXAMPLEDIR}/microwaveoven/build/chip")
set(MICROWAVEOVEN_PORT_FILE       "${MICROWAVEOVEN_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(MICROWAVEOVEN_PORT_ZAP        "${MATTER_EXAMPLEDIR}/microwaveoven/microwaveoven-app.zap")
set(REFRIGERATOR_PORT_OUTPUT_DIR  "${MATTER_EXAMPLEDIR}/refrigerator/build/chip")
set(REFRIGERATOR_PORT_FILE        "${REFRIGERATOR_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(REFRIGERATOR_PORT_ZAP         "${MATTER_EXAMPLEDIR}/refrigerator/refrigerator-app.zap")

# Set Matter files and directories based on the example
#----------------------------------------#
if(MATTER_EXAMPLE STREQUAL "all_clusters")
    set(CLUSTER_FILE ${ALL_CLUSTERS_FILE})
    set(ZAP_FILE     ${ALL_CLUSTERS_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${ALL_CLUSTERS_OUTPUT_DIR})
    file(COPY "${MATTER_EXAMPLEDIR}/chiptest/all-clusters-app.zap"
         DESTINATION "${CHIPDIR}/examples/all-clusters-app/all-clusters-common/")
elseif(MATTER_EXAMPLE STREQUAL "air_purifier")
    set(CLUSTER_FILE ${AIR_PURIFIER_FILE})
    set(ZAP_FILE     ${AIR_PURIFIER_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${AIR_PURIFIER_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "aircon_port")
    set(CLUSTER_FILE ${AIRCON_PORT_FILE})
    set(ZAP_FILE     ${AIRCON_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${AIRCON_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "bridge_dm")
    set(CLUSTER_FILE ${BRIDGE_DM_FILE})
    set(ZAP_FILE     ${BRIDGE_DM_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${BRIDGE_DM_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "bridge_port")
    set(CLUSTER_FILE ${BRIDGE_PORT_FILE})
    set(ZAP_FILE     ${BRIDGE_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${BRIDGE_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "dishwasher_port")
    set(CLUSTER_FILE ${DISHWASHER_PORT_FILE})
    set(ZAP_FILE     ${DISHWASHER_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${DISHWASHER_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "fan_port")
    set(CLUSTER_FILE ${FAN_PORT_FILE})
    set(ZAP_FILE     ${FAN_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${FAN_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "laundrywasher_port")
    set(CLUSTER_FILE ${LAUNDRYWASHER_PORT_FILE})
    set(ZAP_FILE     ${LAUNDRYWASHER_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${LAUNDRYWASHER_PORT_OUTPUT_DIR})
elseif((MATTER_EXAMPLE STREQUAL "light") OR (MATTER_EXAMPLE STREQUAL "light_port") OR (MATTER_EXAMPLE STREQUAL "light_dm"))
    set(CLUSTER_FILE ${LIGHTING_FILE})
    set(ZAP_FILE     ${LIGHTING_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${LIGHTING_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "microwaveoven_port")
    set(CLUSTER_FILE ${MICROWAVEOVEN_PORT_FILE})
    set(ZAP_FILE     ${MICROWAVEOVEN_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${MICROWAVEOVEN_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "refrigerator_port")
    set(CLUSTER_FILE ${REFRIGERATOR_PORT_FILE})
    set(ZAP_FILE     ${REFRIGERATOR_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${REFRIGERATOR_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "thermostat_port")
    set(CLUSTER_FILE ${THERMOSTAT_PORT_FILE})
    set(ZAP_FILE     ${THERMOSTAT_PORT_ZAP})
    string(REPLACE ".zap" ".matter" MATTER_FILE "${ZAP_FILE}")
    set(OUTPUT_DIR ${THERMOSTAT_PORT_OUTPUT_DIR})
else()
    message(FATAL_ERROR "${MATTER_EXAMPLE} example does not exist")
endif()
set(CODEGEN_DIR "${OUTPUT_DIR}/codegen")
set(ARGS_GN "${OUTPUT_DIR}/args.gn")
