set(MATTER_DIR        "${BASEDIR}/component/application/matter")
set(MATTER_CMAKEDIR   "${MATTER_DIR}/project/amebadplus/cmake")
set(CHIPDIR           "${BASEDIR}/third_party/connectedhomeip")
set(MATTER_EXAMPLEDIR "${MATTER_DIR}/example")
set(MATTER_TOOLDIR    "${MATTER_DIR}/tools")

option(CHIP_ENABLE_AMEBA_DLOG    "Enable Logging for Matter"       OFF)
option(CHIP_ENABLE_CHIPOBLE      "Enable BLE for Matter"           ON)
option(CHIP_ENABLE_IPV4          "Enable IPv4 for Matter"          OFF)
option(CHIP_ENABLE_OTA_REQUESTOR "Enable OTA Requestor for Matter" ON)
option(CHIP_ENABLE_SHELL         "Enable Shell for Matter"         ON)
